# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""GPU telemetry collection module for AIPerf.

This module provides GPU telemetry collection capabilities through DCGM endpoints.
"""

########################################################################
## 🚩                     mkinit flags                             🚩 ##
########################################################################
__ignore__ = []
########################################################################
## ⚠️       This file is auto-generated by `make init-files`       ⚠️ ##
## ⚠️                Do not edit below this line                   ⚠️ ##
########################################################################
from aiperf.gpu_telemetry.accumulator import (
    GPUTelemetryAccumulator,
)
from aiperf.gpu_telemetry.constants import (
    DCGM_TO_FIELD_MAPPING,
    GPU_TELEMETRY_COUNTER_METRICS,
    GPU_TELEMETRY_METRICS_CONFIG,
    PYNVML_SOURCE_IDENTIFIER,
    get_gpu_telemetry_metrics_config,
)
from aiperf.gpu_telemetry.dcgm_collector import (
    DCGMTelemetryCollector,
)
from aiperf.gpu_telemetry.factories import (
    GPUTelemetryCollectorFactory,
    GPUTelemetryCollectorProtocol,
    TErrorCallback,
    TRecordCallback,
)
from aiperf.gpu_telemetry.jsonl_writer import (
    GPUTelemetryJSONLWriter,
)
from aiperf.gpu_telemetry.manager import (
    GPUTelemetryManager,
)
from aiperf.gpu_telemetry.metrics_config import (
    MetricsConfigLoader,
)
from aiperf.gpu_telemetry.pynvml_collector import (
    PyNVMLTelemetryCollector,
)

__all__ = [
    "DCGMTelemetryCollector",
    "DCGM_TO_FIELD_MAPPING",
    "GPUTelemetryAccumulator",
    "GPUTelemetryCollectorFactory",
    "GPUTelemetryCollectorProtocol",
    "GPUTelemetryJSONLWriter",
    "GPUTelemetryManager",
    "GPU_TELEMETRY_COUNTER_METRICS",
    "GPU_TELEMETRY_METRICS_CONFIG",
    "MetricsConfigLoader",
    "PYNVML_SOURCE_IDENTIFIER",
    "PyNVMLTelemetryCollector",
    "TErrorCallback",
    "TRecordCallback",
    "get_gpu_telemetry_metrics_config",
]
