# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
########################################################################
## 🚩                     mkinit flags                             🚩 ##
########################################################################
__ignore__ = []
########################################################################
## ⚠️       This file is auto-generated by `make init-files`       ⚠️ ##
## ⚠️                Do not edit below this line                   ⚠️ ##
########################################################################
from aiperf.common.enums.base_enums import (
    BasePydanticBackedStrEnum,
    BasePydanticEnumInfo,
    CaseInsensitiveStrEnum,
    ExtensibleStrEnum,
    ExtensibleStrEnumMeta,
    create_enum,
)
from aiperf.common.enums.command_enums import (
    CommandResponseStatus,
    CommandType,
)
from aiperf.common.enums.communication_enums import (
    CommAddress,
)
from aiperf.common.enums.data_exporter_enums import (
    ExportLevel,
    ServerMetricsFormat,
)
from aiperf.common.enums.dataset_enums import (
    AudioFormat,
    ImageFormat,
    PromptSource,
    PublicDatasetType,
    VideoFormat,
    VideoSynthType,
)
from aiperf.common.enums.logging_enums import (
    AIPerfLogLevel,
)
from aiperf.common.enums.media_enums import (
    MediaType,
)
from aiperf.common.enums.message_enums import (
    MessageType,
)
from aiperf.common.enums.metric_enums import (
    BaseMetricUnit,
    BaseMetricUnitInfo,
    EnergyMetricUnit,
    EnergyMetricUnitInfo,
    FrequencyMetricUnit,
    FrequencyMetricUnitInfo,
    GenericMetricUnit,
    MetricDictValueTypeT,
    MetricFlags,
    MetricOverTimeUnit,
    MetricOverTimeUnitInfo,
    MetricSizeUnit,
    MetricSizeUnitInfo,
    MetricTimeUnit,
    MetricTimeUnitInfo,
    MetricType,
    MetricUnitT,
    MetricValueType,
    MetricValueTypeInfo,
    MetricValueTypeT,
    MetricValueTypeVarT,
    PlotMetricDirection,
    PowerMetricUnit,
    PowerMetricUnitInfo,
    TemperatureMetricUnit,
    TemperatureMetricUnitInfo,
)
from aiperf.common.enums.model_enums import (
    ModelSelectionStrategy,
)
from aiperf.common.enums.plugin_enums import (
    ConnectionReuseStrategy,
)
from aiperf.common.enums.prometheus_enums import (
    PrometheusMetricType,
)
from aiperf.common.enums.service_enums import (
    LifecycleState,
    ServiceRegistrationStatus,
)
from aiperf.common.enums.sse_enums import (
    SSEEventType,
    SSEFieldType,
)
from aiperf.common.enums.system_enums import (
    SystemState,
)
from aiperf.common.enums.telemetry_enums import (
    GPUTelemetryMode,
)
from aiperf.common.enums.timing_enums import (
    CreditPhase,
)
from aiperf.common.enums.worker_enums import (
    WorkerStatus,
)

__all__ = [
    "AIPerfLogLevel",
    "AudioFormat",
    "BaseMetricUnit",
    "BaseMetricUnitInfo",
    "BasePydanticBackedStrEnum",
    "BasePydanticEnumInfo",
    "CaseInsensitiveStrEnum",
    "CommAddress",
    "CommandResponseStatus",
    "CommandType",
    "ConnectionReuseStrategy",
    "CreditPhase",
    "EnergyMetricUnit",
    "EnergyMetricUnitInfo",
    "ExportLevel",
    "ExtensibleStrEnum",
    "ExtensibleStrEnumMeta",
    "FrequencyMetricUnit",
    "FrequencyMetricUnitInfo",
    "GPUTelemetryMode",
    "GenericMetricUnit",
    "ImageFormat",
    "LifecycleState",
    "MediaType",
    "MessageType",
    "MetricDictValueTypeT",
    "MetricFlags",
    "MetricOverTimeUnit",
    "MetricOverTimeUnitInfo",
    "MetricSizeUnit",
    "MetricSizeUnitInfo",
    "MetricTimeUnit",
    "MetricTimeUnitInfo",
    "MetricType",
    "MetricUnitT",
    "MetricValueType",
    "MetricValueTypeInfo",
    "MetricValueTypeT",
    "MetricValueTypeVarT",
    "ModelSelectionStrategy",
    "PlotMetricDirection",
    "PowerMetricUnit",
    "PowerMetricUnitInfo",
    "PrometheusMetricType",
    "PromptSource",
    "PublicDatasetType",
    "SSEEventType",
    "SSEFieldType",
    "ServerMetricsFormat",
    "ServiceRegistrationStatus",
    "SystemState",
    "TemperatureMetricUnit",
    "TemperatureMetricUnitInfo",
    "VideoFormat",
    "VideoSynthType",
    "WorkerStatus",
    "create_enum",
]
