# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Plugin schema definitions and JSON schema files."""

########################################################################
## 🚩                     mkinit flags                             🚩 ##
########################################################################
__ignore__ = []
########################################################################
## ⚠️       This file is auto-generated by `make init-files`       ⚠️ ##
## ⚠️                Do not edit below this line                   ⚠️ ##
########################################################################
from aiperf.plugin.schema.schemas import (
    CategoriesManifest,
    CategorySpec,
    PackageInfo,
    PluginsManifest,
    PluginSpec,
)

__all__ = [
    "CategoriesManifest",
    "CategorySpec",
    "PackageInfo",
    "PluginSpec",
    "PluginsManifest",
]
