# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Plugin schema definitions and JSON schema files."""

########################################################################
## 🚩                     mkinit flags                             🚩 ##
########################################################################
__ignore__ = []
########################################################################
## ⚠️       This file is auto-generated by `make init-files`       ⚠️ ##
## ⚠️                Do not edit below this line                   ⚠️ ##
########################################################################
from aiperf.plugin.schema.schemas import (
    CategoriesFile,
    CategorySpec,
    PluginPackageInfo,
    PluginsFile,
    PluginTypeEntry,
)

__all__ = [
    "CategoriesFile",
    "CategorySpec",
    "PluginPackageInfo",
    "PluginTypeEntry",
    "PluginsFile",
]
