# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""AIPerf API module.

Provides a unified HTTP + WebSocket API for:
- Prometheus metrics scraping (/metrics)
- JSON metrics API (/api/metrics)
- Benchmark status and progress (/api/status, /api/progress)
- Real-time ZMQ message streaming via WebSocket (/ws)
"""

########################################################################
## 🚩                     mkinit flags                             🚩 ##
########################################################################
__ignore__ = []
# The list of submodules is intentionally left empty to prevent
# automatically importing everything from submodules into the top-level namespace.
# This means consumers must explicitly import from submodules as needed.
__submodules__ = []
########################################################################
## ⚠️       This file is auto-generated by `make init-files`       ⚠️ ##
## ⚠️                Do not edit below this line                   ⚠️ ##
########################################################################
__all__ = []
