# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# ============================================================================
# AUTO-GENERATED FILE - DO NOT EDIT
# ============================================================================
# Generated by: tools/generate_plugin_enums.py
# Sources: src/aiperf/plugin/categories.yaml, src/aiperf/plugin/plugins.yaml
#
# To regenerate: make generate-plugin-enums
# ============================================================================
"""
Plugin Type Enums

Type enums for all plugin categories, generated dynamically from the plugin registry.
These enums work with pydantic validation, cyclopts CLI parsing, and support
compile-time checks (e.g., `if ui_type == UIType.DASHBOARD`).

New plugins registered at runtime automatically extend the appropriate enum.

Usage:
    from aiperf.plugin.enums import EndpointType, UIType
    # or
    from aiperf.plugin import EndpointType, UIType
"""

from typing import TYPE_CHECKING

from aiperf.common.enums import create_enum
from aiperf.plugin import plugins

# ============================================================================
# Plugin Protocol Categories
# ============================================================================

if TYPE_CHECKING:
    # Import the enum from the stubs file
    from aiperf.plugin.enums import PluginCategory
else:
    # Create runtime enum with all plugin category names from the registry
    _all_plugin_categories = plugins.list_categories()
    PluginCategory = create_enum(
        "PluginCategory",
        {
            category.replace("-", "_").upper(): category
            for category in _all_plugin_categories
        },
    )
    """
    Dynamic enum for plugin categories.

    Members are auto-generated from registered plugin categories in plugins.yaml.
    Example: PluginCategory.ENDPOINT, PluginCategory.UI, PluginCategory.TRANSPORT, etc.
    """

# ============================================================================
# Endpoint and Transport Types
# ============================================================================

TransportType = plugins.create_enum(PluginCategory.TRANSPORT, "TransportType")
"""
Dynamic enum for transport implementations.

Members are auto-generated from registered transport plugins.
Example: TransportType.HTTP
"""

# ============================================================================
# Processing Types
# ============================================================================

RecordProcessorType = plugins.create_enum(
    PluginCategory.RECORD_PROCESSOR, "RecordProcessorType"
)
"""
Dynamic enum for record processor implementations.

Members are auto-generated from registered record processor plugins.
Example: RecordProcessorType.METRIC_RECORD, RecordProcessorType.RAW_RECORD_WRITER
"""

ResultsProcessorType = plugins.create_enum(
    PluginCategory.RESULTS_PROCESSOR, "ResultsProcessorType"
)
"""
Dynamic enum for results processor implementations.

Members are auto-generated from registered results processor plugins.
Example: ResultsProcessorType.GPU_TELEMETRY_ACCUMULATOR, ResultsProcessorType.GPU_TELEMETRY_JSONL_WRITER, ResultsProcessorType.METRIC_RESULTS
"""

# ============================================================================
# Export Types
# ============================================================================

DataExporterType = plugins.create_enum(PluginCategory.DATA_EXPORTER, "DataExporterType")
"""
Dynamic enum for data exporter implementations.

Members are auto-generated from registered data exporter plugins.
Example: DataExporterType.CSV, DataExporterType.JSON, DataExporterType.RAW_RECORD_AGGREGATOR
"""

ConsoleExporterType = plugins.create_enum(
    PluginCategory.CONSOLE_EXPORTER, "ConsoleExporterType"
)
"""
Dynamic enum for console exporter implementations.

Members are auto-generated from registered console exporter plugins.
Example: ConsoleExporterType.API_ERRORS, ConsoleExporterType.ERRORS, ConsoleExporterType.EXPERIMENTAL_METRICS
"""

# ============================================================================
# UI Types
# ============================================================================

UIType = plugins.create_enum(PluginCategory.UI, "UIType")
"""
Dynamic enum for ui implementations.

Members are auto-generated from registered ui plugins.
Example: UIType.DASHBOARD, UIType.NONE, UIType.SIMPLE
"""

# ============================================================================
# Service Types
# ============================================================================

ServiceType = plugins.create_enum(PluginCategory.SERVICE, "ServiceType")
"""
Dynamic enum for service implementations.

Members are auto-generated from registered service plugins.
Example: ServiceType.DATASET_MANAGER, ServiceType.GPU_TELEMETRY_MANAGER, ServiceType.RECORD_PROCESSOR
"""

ServiceRunType = plugins.create_enum(PluginCategory.SERVICE_MANAGER, "ServiceRunType")
"""
Dynamic enum for service manager implementations.

Members are auto-generated from registered service manager plugins.
Example: ServiceRunType.KUBERNETES, ServiceRunType.MULTIPROCESSING
"""

__all__ = [
    "ConsoleExporterType",
    "DataExporterType",
    "PluginCategory",
    "RecordProcessorType",
    "ResultsProcessorType",
    "ServiceRunType",
    "ServiceType",
    "TransportType",
    "UIType",
]
