# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# ============================================================================
# AUTO-GENERATED FILE - DO NOT EDIT
# ============================================================================
# Generated by: tools/generate_plugin_enums.py
# Sources: src/aiperf/plugin/categories.yaml, src/aiperf/plugin/plugins.yaml
#
# To regenerate: make generate-plugin-enums
# ============================================================================
"""
Plugin Type Enums

Type enums for all plugin categories, generated dynamically from the plugin registry.
These enums work with pydantic validation, cyclopts CLI parsing, and support
compile-time checks (e.g., `if ui_type == UIType.DASHBOARD`).

New plugins registered at runtime automatically extend the appropriate enum.

Usage:
    from aiperf.plugin.enums import EndpointType, UIType
    # or
    from aiperf.plugin import EndpointType, UIType
"""

from typing import TYPE_CHECKING

from aiperf.common.enums import create_enum
from aiperf.plugin import plugin_registry

# ============================================================================
# Plugin Protocol Categories
# ============================================================================

if TYPE_CHECKING:
    # Import the enum from the stubs file
    from aiperf.plugin.enums import PluginCategory
else:
    # Create runtime enum with all plugin category names from the registry
    _all_plugin_categories = plugin_registry.list_categories()
    PluginCategory = create_enum(
        "PluginCategory",
        {
            category.replace("-", "_").upper(): category
            for category in _all_plugin_categories
        },
    )
    """
    Dynamic enum for plugin categories.

    Members are auto-generated from registered plugin categories in plugins.yaml.
    Example: PluginCategory.ENDPOINT, PluginCategory.UI, PluginCategory.TRANSPORT, etc.
    """

# ============================================================================
# Timing Types
# ============================================================================

TimingMode = plugin_registry.create_enum(PluginCategory.TIMING_STRATEGY, "TimingMode")
"""
Dynamic enum for timing strategy implementations.

Members are auto-generated from registered timing strategy plugins.
Example: TimingMode.FIXED_SCHEDULE, TimingMode.REQUEST_RATE, TimingMode.USER_CENTRIC_RATE
"""

ArrivalPattern = plugin_registry.create_enum(
    PluginCategory.ARRIVAL_PATTERN, "ArrivalPattern"
)
"""
Dynamic enum for arrival pattern implementations.

Members are auto-generated from registered arrival pattern plugins.
Example: ArrivalPattern.CONCURRENCY_BURST, ArrivalPattern.CONSTANT, ArrivalPattern.GAMMA
"""

RampType = plugin_registry.create_enum(PluginCategory.RAMP, "RampType")
"""
Dynamic enum for ramp implementations.

Members are auto-generated from registered ramp plugins.
Example: RampType.EXPONENTIAL, RampType.LINEAR, RampType.POISSON
"""

# ============================================================================
# Dataset Types
# ============================================================================

DatasetBackingStoreType = plugin_registry.create_enum(
    PluginCategory.DATASET_BACKING_STORE, "DatasetBackingStoreType"
)
"""
Dynamic enum for dataset backing store implementations.

Members are auto-generated from registered dataset backing store plugins.
Example: DatasetBackingStoreType.MEMORY_MAP
"""

DatasetClientStoreType = plugin_registry.create_enum(
    PluginCategory.DATASET_CLIENT_STORE, "DatasetClientStoreType"
)
"""
Dynamic enum for dataset client store implementations.

Members are auto-generated from registered dataset client store plugins.
Example: DatasetClientStoreType.MEMORY_MAP
"""

DatasetSamplingStrategy = plugin_registry.create_enum(
    PluginCategory.DATASET_SAMPLER, "DatasetSamplingStrategy"
)
"""
Dynamic enum for dataset sampler implementations.

Members are auto-generated from registered dataset sampler plugins.
Example: DatasetSamplingStrategy.RANDOM, DatasetSamplingStrategy.SEQUENTIAL, DatasetSamplingStrategy.SHUFFLE
"""

ComposerType = plugin_registry.create_enum(
    PluginCategory.DATASET_COMPOSER, "ComposerType"
)
"""
Dynamic enum for dataset composer implementations.

Members are auto-generated from registered dataset composer plugins.
Example: ComposerType.CUSTOM, ComposerType.SYNTHETIC, ComposerType.SYNTHETIC_RANKINGS
"""

CustomDatasetType = plugin_registry.create_enum(
    PluginCategory.CUSTOM_DATASET_LOADER, "CustomDatasetType"
)
"""
Dynamic enum for custom dataset loader implementations.

Members are auto-generated from registered custom dataset loader plugins.
Example: CustomDatasetType.MOONCAKE_TRACE, CustomDatasetType.MULTI_TURN, CustomDatasetType.RANDOM_POOL
"""

# ============================================================================
# Endpoint and Transport Types
# ============================================================================

EndpointType = plugin_registry.create_enum(PluginCategory.ENDPOINT, "EndpointType")
"""
Dynamic enum for endpoint implementations.

Members are auto-generated from registered endpoint plugins.
Example: EndpointType.CHAT, EndpointType.COHERE_RANKINGS, EndpointType.COMPLETIONS
"""

TransportType = plugin_registry.create_enum(PluginCategory.TRANSPORT, "TransportType")
"""
Dynamic enum for transport implementations.

Members are auto-generated from registered transport plugins.
Example: TransportType.HTTP
"""

# ============================================================================
# Processing Types
# ============================================================================

RecordProcessorType = plugin_registry.create_enum(
    PluginCategory.RECORD_PROCESSOR, "RecordProcessorType"
)
"""
Dynamic enum for record processor implementations.

Members are auto-generated from registered record processor plugins.
Example: RecordProcessorType.METRIC_RECORD, RecordProcessorType.RAW_RECORD_WRITER
"""

ResultsProcessorType = plugin_registry.create_enum(
    PluginCategory.RESULTS_PROCESSOR, "ResultsProcessorType"
)
"""
Dynamic enum for results processor implementations.

Members are auto-generated from registered results processor plugins.
Example: ResultsProcessorType.GPU_TELEMETRY_ACCUMULATOR, ResultsProcessorType.GPU_TELEMETRY_JSONL_WRITER, ResultsProcessorType.METRIC_RESULTS
"""

# ============================================================================
# Export Types
# ============================================================================

DataExporterType = plugin_registry.create_enum(
    PluginCategory.DATA_EXPORTER, "DataExporterType"
)
"""
Dynamic enum for data exporter implementations.

Members are auto-generated from registered data exporter plugins.
Example: DataExporterType.CSV, DataExporterType.JSON, DataExporterType.RAW_RECORD_AGGREGATOR
"""

ConsoleExporterType = plugin_registry.create_enum(
    PluginCategory.CONSOLE_EXPORTER, "ConsoleExporterType"
)
"""
Dynamic enum for console exporter implementations.

Members are auto-generated from registered console exporter plugins.
Example: ConsoleExporterType.API_ERRORS, ConsoleExporterType.ERRORS, ConsoleExporterType.EXPERIMENTAL_METRICS
"""

# ============================================================================
# UI Types
# ============================================================================

UIType = plugin_registry.create_enum(PluginCategory.UI, "UIType")
"""
Dynamic enum for ui implementations.

Members are auto-generated from registered ui plugins.
Example: UIType.DASHBOARD, UIType.NONE, UIType.SIMPLE
"""

# ============================================================================
# Service Types
# ============================================================================

ServiceType = plugin_registry.create_enum(PluginCategory.SERVICE, "ServiceType")
"""
Dynamic enum for service implementations.

Members are auto-generated from registered service plugins.
Example: ServiceType.DATASET_MANAGER, ServiceType.GPU_TELEMETRY_MANAGER, ServiceType.RECORD_PROCESSOR
"""

ServiceRunType = plugin_registry.create_enum(
    PluginCategory.SERVICE_MANAGER, "ServiceRunType"
)
"""
Dynamic enum for service manager implementations.

Members are auto-generated from registered service manager plugins.
Example: ServiceRunType.KUBERNETES, ServiceRunType.MULTIPROCESSING
"""

# ============================================================================
# Communication Types
# ============================================================================

CommunicationBackend = plugin_registry.create_enum(
    PluginCategory.COMMUNICATION, "CommunicationBackend"
)
"""
Dynamic enum for communication implementations.

Members are auto-generated from registered communication plugins.
Example: CommunicationBackend.ZMQ_IPC, CommunicationBackend.ZMQ_TCP
"""

CommClientType = plugin_registry.create_enum(
    PluginCategory.COMMUNICATION_CLIENT, "CommClientType"
)
"""
Dynamic enum for communication client implementations.

Members are auto-generated from registered communication client plugins.
Example: CommClientType.PUB, CommClientType.PULL, CommClientType.PUSH
"""

ZMQProxyType = plugin_registry.create_enum(PluginCategory.ZMQ_PROXY, "ZMQProxyType")
"""
Dynamic enum for zmq proxy implementations.

Members are auto-generated from registered zmq proxy plugins.
Example: ZMQProxyType.DEALER_ROUTER, ZMQProxyType.PUSH_PULL, ZMQProxyType.XPUB_XSUB
"""

# ============================================================================
# Visualization Types
# ============================================================================

PlotType = plugin_registry.create_enum(PluginCategory.PLOT, "PlotType")
"""
Dynamic enum for plot implementations.

Members are auto-generated from registered plot plugins.
Example: PlotType.AREA, PlotType.DUAL_AXIS, PlotType.HISTOGRAM
"""

__all__ = [
    "ArrivalPattern",
    "CommClientType",
    "CommunicationBackend",
    "ComposerType",
    "ConsoleExporterType",
    "CustomDatasetType",
    "DataExporterType",
    "DatasetBackingStoreType",
    "DatasetClientStoreType",
    "DatasetSamplingStrategy",
    "EndpointType",
    "PlotType",
    "PluginCategory",
    "RampType",
    "RecordProcessorType",
    "ResultsProcessorType",
    "ServiceRunType",
    "ServiceType",
    "TimingMode",
    "TransportType",
    "UIType",
    "ZMQProxyType",
]
