# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from pathlib import Path
from typing import Annotated

from pydantic import Field

from aiperf.common.config.base_config import BaseConfig
from aiperf.common.config.cli_parameter import CLIParameter
from aiperf.common.config.config_defaults import OutputDefaults
from aiperf.common.config.groups import Groups
from aiperf.common.enums import ExportLevel


class OutputConfig(BaseConfig):
    """
    A configuration class for defining output related settings.
    """

    _CLI_GROUP = Groups.OUTPUT

    base_artifact_directory: Annotated[
        Path,
        Field(
            description="The base directory to store all the (output) artifacts generated by AIPerf.",
        ),
        CLIParameter(
            name=(
                "--base-artifact-dir",
                "--output-artifact-dir",
                "--artifact-dir",  # GenAI-Perf
            ),
            group=_CLI_GROUP,
        ),
    ] = OutputDefaults.ARTIFACT_DIRECTORY

    profile_export_prefix: Annotated[
        Path | None,
        Field(
            description="The prefix for the profile export file names. Will be suffixed with .csv, .json, .jsonl, and _raw.jsonl."
            "If not provided, the default profile export file names will be used: profile_export_aiperf.csv, profile_export_aiperf.json, "
            "profile_export.jsonl, and profile_export_raw.jsonl.",
        ),
        CLIParameter(
            name=(
                "--profile-export-prefix",
                "--profile-export-file",  # GenAI-Perf
            ),
            group=_CLI_GROUP,
        ),
    ] = None

    export_level: Annotated[
        ExportLevel,
        Field(
            description="The level of profile export files to create.",
        ),
        CLIParameter(
            name=("--export-level", "--profile-export-level"),
            group=_CLI_GROUP,
        ),
    ] = OutputDefaults.EXPORT_LEVEL

    slice_duration: Annotated[
        float | None,
        Field(
            description="The duration (in seconds) of an individual time slice to be used post-benchmark in time-slicing mode.",
        ),
        CLIParameter(
            name=("--slice-duration"),
            group=_CLI_GROUP,
        ),
    ] = OutputDefaults.SLICE_DURATION
